[package]
name = "ttd-v4"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "0.12.15", features = ["blocking"]}
scraper = "0.23.1"
slint = {version = "1.11.0", features = ["renderer-skia"]}

[build-dependencies]
slint-build = "1.11.0"
