import {UiData, DayAnime, AnimeData} from "global.slint";

import { TabWidget, StandardTableView, GroupBox, ScrollView, ListView, Button } from "std-widgets.slint";
export component Anime inherits VerticalLayout {
    width: 100%;
    padding-top: UiData.tab-padding-top-bottom;
    padding-bottom: UiData.tab-padding-top-bottom;
    padding-left: UiData.tab-padding-left-right;
    padding-right: UiData.tab-padding-left-right;
    HorizontalLayout {
        spacing: UiData.space;
        padding-left: UiData.padding;
        alignment: start;
        Text {
        text: "新番日历-数据源长门有C";
        font-size: UiData.font-size-big;
        vertical-alignment: center;
        }
        Button {
            text: "上一季度";
            clicked => { AnimeData.previous_schedule();}
        }
        Text {
            text: AnimeData.anime-schedule.year + "年" + AnimeData.anime-schedule.month + "月番";
            font-size: UiData.font-size-big;
            vertical-alignment: center;
        }
        Button {
            text: "下一季度";
            clicked => { AnimeData.next_schedule();}
        }
    }

    ListView {
        for day-anime in AnimeData.week-anime-list: VerticalLayout {
            padding: UiData.padding;
            spacing: UiData.space;
            Rectangle {
                background: UiData.primary-color;
                border-radius: UiData.border-radius;
                height: UiData.anime-list-title-height;
                width: 100%;
                Text {
                    text: day-anime.text;
                    horizontal-alignment: center;
                    font-size: UiData.font-size-big;
                    color: UiData.secondry-text-color;
                }
            }

            HorizontalLayout {
                spacing: UiData.space;
                for anime in day-anime.anime-list: VerticalLayout {
                    Rectangle {
                        width: 120px;
                        height: 150px;
                        border-radius: UiData.border-radius;
                        clip: true;
                        Image {
                        source: anime.cover;
                        width: 100%;
                        height: 100%;
                    }
                    }

                    Text {
                        width: 120px;
                        text: anime.name;
                        wrap: word-wrap;
                        horizontal-alignment: center;
                    }
                }
            }
        }
    }
}
