import {Button, HorizontalBox, VerticalBox, TabWidget} from "std-widgets.slint";
import {Todo} from "./todo.slint";
import "./assets/font/LXGWWenKaiGBScreen.ttf";
import { Menu } from "menu.slint";


export component AppWindow inherits Window {
    default-font-family: "霞鹜文楷 GB 屏幕阅读版";
    default-font-size: 16px;
    preferred-height: 720px;
    preferred-width: 1280px;
    HorizontalLayout {
        Menu {}

    }
} 