import {Button, HorizontalBox, VerticalBox, TabWidget} from "std-widgets.slint";
import {Todo} from "./todo.slint";
import "./assets/font/LXGWWenKaiMonoGBScreen.ttf";
import { Menu } from "menu.slint";
import { Anime } from "anime.slint";
import { UiData, Tab, AnimeData, TodoData } from "global.slint";
import { About } from "about.slint";

export { AnimeData, TodoData }



export component AppWindow inherits Window {
    default-font-family: "LXGW WenKai Mono GB Screen";
    default-font-size: UiData.default-font-size;
    preferred-height: UiData.app-height;
    preferred-width: UiData.app-width;
    HorizontalLayout {
        Rectangle {
            height: 100%;
            width: 15%;
            background: UiData.primary-color;
            Menu { }
        }

        Rectangle {
            width: 85%;
            height: 100%;
            if UiData.current-tab == Tab.Todo: Todo {}
            if UiData.current-tab == Tab.Anime: Anime {}
            if UiData.current-tab == Tab.About: About {}
        }
    }
}
