import {Date} from "std-widgets.slint";

export global UiData {
    out property <int> spinbox-max: 10000;
    in-out property <length> spinbox-width: 120px;
    in-out property <length> combobox-width: 100px;
    in-out property <length> space: 5px;
    in-out property <length> padding: 5px;
    in-out property <color> menu-background: #82AA82; //TODO: 要不要
    in-out property <length> menu-button-height: 60px;
    in-out property <color> menu-button-background: #82AA82;
    in-out property <length> menu-button-font-size: 20px;
    out property <Date> default-date: {
        year: 2025,
        month: 1,
        day: 1
    };
}

struct Todo {
    text: string,
    created-at: string,
    type: string,
    rank: string
}

export global TodoData {
    in-out property <[Todo]> todo-list;
}
