

import { UiData, Tab } from "global.slint";
import { VerticalBox } from "std-widgets.slint";
export component Menu inherits VerticalLayout {
    width: 100%;
    Rectangle {
        height: 25%;
        width: 100%;
        logo := Rectangle {
            clip: true;
            height: logo.width;
            width: 40%;
            border-radius: logo.height / 2;
            Image {
                width: 100%;
                height: 100%;
                source: @image-url("assets/img/avatar.jpg");
            }
        }
    }
    VerticalLayout {
        alignment: start;
        spacing: UiData.space;
        Rectangle {
            height: UiData.menu-button-height;
            width: 100%;
            Text {
                text: "主页";
                font-size: UiData.menu-button-font-size;
                color: UiData.secondry-text-color;
            }
            TouchArea {
                clicked => {
                    UiData.current-tab = Tab.Home;
                }
            }
            states [
                active when UiData.current-tab == Tab.Home:  {
                    background: UiData.menu-button-clicked-color;
                }
            ]
        }
        Rectangle {
            height: UiData.menu-button-height;
            width: 100%;
            Text {
                text: "待办";
                font-size: UiData.menu-button-font-size;
                color: UiData.secondry-text-color;
            }
            TouchArea {
                clicked => {
                    UiData.current-tab = Tab.Todo;
                }
            }
            states [
                active when UiData.current-tab == Tab.Todo:  {
                    background: UiData.menu-button-clicked-color;
                }
            ]
        }
        Rectangle {
            height: UiData.menu-button-height;
            width: 100%;
            Text {
                text: "番剧";
                font-size: UiData.menu-button-font-size;
                color: UiData.secondry-text-color;
            }
            TouchArea {
                clicked => {
                    UiData.current-tab = Tab.Anime;
                }
            }
            states [
                active when UiData.current-tab == Tab.Anime:  {
                    background: UiData.menu-button-clicked-color;
                }
            ]
        }
        Rectangle {
            height: UiData.menu-button-height;
            width: 100%;
            Text {
                text: "新闻";
                font-size: UiData.menu-button-font-size;
                color: UiData.secondry-text-color;
            }
            TouchArea {
                clicked => {
                    UiData.current-tab = Tab.News;
                }
            }
            states [
                active when UiData.current-tab == Tab.News:  {
                    background: UiData.menu-button-clicked-color;
                }
            ]
        }
        Rectangle {
            height: UiData.menu-button-height;
            width: 100%;
            Text {
                text: "统计";
                font-size: UiData.menu-button-font-size;
                color: UiData.secondry-text-color;
            }
            TouchArea {
                clicked => {
                    UiData.current-tab = Tab.Stats;
                }
            }
            states [
                active when UiData.current-tab == Tab.Stats:  {
                    background: UiData.menu-button-clicked-color;
                }
            ]
        }
        
    }
    VerticalLayout {
        alignment: end;
        height: 20%;
        width: 100%;
        Rectangle {
            height: UiData.menu-button-height;
            width: 100%;
            Text {
                text: "设置";
                font-size: UiData.menu-button-font-size;
                color: UiData.secondry-text-color;
            }
        }
    }
}
