

import { UiData, Tab } from "global.slint";
import { VerticalBox } from "std-widgets.slint";
export component Menu inherits VerticalLayout {
    width: 100%;
    Rectangle {
        height: 25%;
        width: 100%;
        Rectangle {
            clip: true;
            height: UiData.avatar-size;
            width: UiData.avatar-size;
            border-radius: UiData.avatar-size / 2;
            Image {
                width: 100%;
                height: 100%;
                source: @image-url("assets/img/avatar.jpg");
            }
            ta := TouchArea {
                
            }
            states [
               active when ta.has-hover: {
                width: UiData.avatar-size-big;
                height: UiData.avatar-size-big;
                border-radius: UiData.avatar-size-big / 2;
               }
            ]
            animate width, height, border-radius {
                duration: 0.3s;
                easing: ease-in-out;
            }
        }
    }

    VerticalLayout {
        alignment: start;
        spacing: UiData.space;
        vertical-stretch: 1;
        padding-left: UiData.tab-padding-left-right;
        padding-right: UiData.tab-padding-left-right;
        Rectangle {
            border-radius: UiData.border-radius;
            height: UiData.menu-button-height;
            width: 100%;
            Text {
                text: "主页";
                font-size: UiData.menu-button-font-size;
                color: UiData.secondry-text-color;
            }

            TouchArea {
                clicked => {
                    UiData.current-tab = Tab.Home;
                }
            }

            states [
                active when UiData.current-tab == Tab.Home: {
                    background: UiData.menu-button-clicked-color;
                }
            ]
            animate background {
                duration: 0.2s;
                easing: ease-in-out;
            }
        }

        Rectangle {
            border-radius: UiData.border-radius;
            height: UiData.menu-button-height;
            width: 100%;
            Text {
                text: "待办";
                font-size: UiData.menu-button-font-size;
                color: UiData.secondry-text-color;
            }

            TouchArea {
                clicked => {
                    UiData.current-tab = Tab.Todo;
                }
            }

            states [
                active when UiData.current-tab == Tab.Todo: {
                    background: UiData.menu-button-clicked-color;
                }
            ]
            animate background {
                duration: 0.2s;
                easing: ease-in-out;
            }
        }

        Rectangle {
            border-radius: UiData.border-radius;
            height: UiData.menu-button-height;
            width: 100%;
            Text {
                text: "番剧";
                font-size: UiData.menu-button-font-size;
                color: UiData.secondry-text-color;
            }

            TouchArea {
                clicked => {
                    UiData.current-tab = Tab.Anime;
                }
            }

            states [
                active when UiData.current-tab == Tab.Anime: {
                    background: UiData.menu-button-clicked-color;
                }
            ]
            animate background {
                duration: 0.2s;
                easing: ease-in-out;
            }
        }

        Rectangle {
            border-radius: UiData.border-radius;
            height: UiData.menu-button-height;
            width: 100%;
            Text {
                text: "新闻";
                font-size: UiData.menu-button-font-size;
                color: UiData.secondry-text-color;
            }

            TouchArea {
                clicked => {
                    UiData.current-tab = Tab.News;
                }
            }

            states [
                active when UiData.current-tab == Tab.News: {
                    background: UiData.menu-button-clicked-color;
                }
            ]
            animate background {
                duration: 0.2s;
                easing: ease-in-out;
            }
        }

        Rectangle {
            border-radius: UiData.border-radius;
            height: UiData.menu-button-height;
            width: 100%;
            Text {
                text: "统计";
                font-size: UiData.menu-button-font-size;
                color: UiData.secondry-text-color;
            }

            TouchArea {
                clicked => {
                    UiData.current-tab = Tab.Stats;
                }
            }

            states [
                active when UiData.current-tab == Tab.Stats: {
                    background: UiData.menu-button-clicked-color;
                }
            ]
            animate background {
                duration: 0.2s;
                easing: ease-in-out;
            }
        }
    }

    VerticalLayout {
        width: 100%;
        padding-left: UiData.tab-padding-left-right;
        padding-right: UiData.tab-padding-left-right;
        padding-bottom: UiData.tab-padding-top-bottom;
        Rectangle {
            border-radius: UiData.border-radius;
            height: UiData.menu-button-height;
            width: 100%;
            Text {
                text: "关于";
                font-size: UiData.menu-button-font-size;
                color: UiData.secondry-text-color;
            }

            TouchArea {
                clicked => {
                    UiData.current-tab = Tab.About;
                }
            }

            states [
                active when UiData.current-tab == Tab.About: {
                    background: UiData.menu-button-clicked-color;
                }
            ]
            animate background {
                duration: 0.2s;
                easing: ease-in-out;
            }
        }
    }
}
