import {Date, Button, LineEdit, HorizontalBox, CheckBox, ComboBox, VerticalBox, DatePickerPopup, Slider, SpinBox, Spinner, TabWidget, GroupBox, GridBox, ListView, ScrollView} from "std-widgets.slint";
import { Filter, Todo, TodoData, TodoKind, UiData, Icons } from "global.slint";


component TodoCard inherits Rectangle {
    function day-suffix(day: int) -> string {
        if day == 1 || day == 21 || day == 31 {
            return "st";
        } else if day == 2 || day == 22 {
            return "nd";
        } else if day == 3 || day == 23 {
            return "rd";
        } else {
            return "th";
        }
    }
    //不满10增加0前缀
    function day-prefix(day: int) -> string {
        if day < 10 {
            return "0" + day;
        } else {
            return day;
        }
    }
    in-out property <int> day;
    in-out property <[Todo]> todo-list;
    background: UiData.primary-color;
    border-radius: UiData.border-radius;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: UiData.padding;
        spacing: UiData.space;
        HorizontalLayout {
            padding-left: UiData.padding;
            alignment: start;
            Text {
                text: day-prefix(day);
                vertical-alignment: center;
                height: UiData.calendar-index-size;
                font-size: UiData.calendar-index-size;
                color: day == 0 ? UiData.primary-color : UiData.secondry-text-color;
            }

            VerticalLayout {
                alignment: end;
                Text {
                    text: day-suffix(day);
                    font-size: UiData.font-size-big;
                    color: day == 0 ? UiData.primary-color : UiData.secondry-text-color;
                }
            }
        }

        ListView {
            for todo[i] in todo-list: Text {
                text: (i + 1) + "." + todo.text;
                overflow: elide;
                color: UiData.secondry-text-color;
                font-size: UiData.font-size-small;
            }
        }
    }
}

export component Todo inherits HorizontalLayout {
    height: 100%;
    width: 100%;
    padding-top: UiData.tab-padding-top-bottom;
    padding-bottom: UiData.tab-padding-top-bottom;
    padding-left: UiData.tab-padding-left-right;
    padding-right: UiData.tab-padding-left-right;
    spacing: UiData.space-big;
    property <[string]> todo-type: ["单次", "每日", "每周", "每月", "进度"];
    property <[string]> weeks: ["周一", "周二", "周三", "周四", "周五", "周六", "周日"];
    property <int> day: 1;
    in-out property <string> pop-window-text;
    function input_check() -> bool {
        if (text-le.text.is-empty) {
            pop-window-text = "待办内容不能为空！";
            return false;
        } else if (TodoData.new-todo.kind == TodoKind.Once && TodoData.new-todo.once < TodoData.current-date) {
            pop-window-text = "单次待办日期不能早于今天！";
            return false;
        } else if (TodoData.new-todo.end-date < TodoData.current-date && TodoData.new-todo.kind != TodoKind.Once) {
            pop-window-text = "待办截止日期不能早于今天！";
            return false;
        } else if (TodoData.new-todo.start-date >= TodoData.new-todo.end-date && TodoData.new-todo.kind != TodoKind.Once) {
            pop-window-text = "待办起始日期必须早于截止日期！";
            return false;
        } else if (!TodoData.duration-check(TodoData.new-todo)) {
            pop-window-text = "起止时间段内没有有效的待办日期!";
            return false;
        } else {
            return true;
        }
    }
    function add-todo() {
        if (!input_check()) {
            pop.show();
            return;
        }
        TodoData.new-todo.text = text-le.text;
        TodoData.new-todo.note = note-le.text;
        TodoData.add-todo(TodoData.new-todo);
        filter-rt.selected-index = 1;
        TodoData.filter = Filter.All;
        reset(); //TODO 失去焦点
    }
    function reset() {
        TodoData.new-todo = TodoData.default-todo;
        type-cb.current-index = 0;
        text-le.text = "";
        note-le.text = ""; // TODO 还有别的加上 
    }
    date-picker-once := DatePickerPopup {
        close-policy: PopupClosePolicy.close-on-click-outside;
        accepted(date) => {
            TodoData.new-todo.once = date;
            self.close();
        }
        canceled => {
            self.close();
        }
    }

    date-picker-start-date := DatePickerPopup {
        close-policy: PopupClosePolicy.close-on-click-outside;
        accepted(date) => {
            TodoData.new-todo.start-date = date;
            self.close();
        }
        canceled => {
            self.close();
        }
    }

    date-picker-end-date := DatePickerPopup {
        close-policy: PopupClosePolicy.close-on-click-outside;
        accepted(date) => {
            TodoData.new-todo.end-date = date;
            self.close();
        }
        canceled => {
            self.close();
        }
    }

    VerticalLayout {
        width: parent.width * 0.4;
        spacing: UiData.space;
        HorizontalLayout {
            spacing: UiData.space;
            pop := PopupWindow {
                width: UiData.pop-window-width;
                height: UiData.pop-window-height;
                x: (parent.width - self.width) / 2;
                y: UiData.pop-window-y;
                Rectangle {
                    width: 100%;
                    height: 100%;
                    background: UiData.primary-color;
                    border-radius: UiData.border-radius;
                    drop-shadow-offset-y: UiData.pop-window-shadow-y;
                    drop-shadow-blur: UiData.pop-window-shadow-blur;
                    drop-shadow-color: UiData.pop-window-shadow-color;
                    Text {
                        text: pop-window-text;
                        font-size: UiData.font-size-big;
                        color: UiData.secondry-text-color;
                    }
                }
            }

            type-cb := ComboBox {
                width: parent.width * 0.25;
                model: todo-type;
                selected(_) => {
                    TodoData.new-todo.kind = TodoData.convert-int-to-todokind(self.current-index);
                    if TodoData.new-todo.kind == TodoKind.Once || TodoData.new-todo.kind == TodoKind.Progress {
                        TodoData.new-todo.recurrence = false;
                    } else {
                        TodoData.new-todo.recurrence = true;
                    }
                }
            }

            if TodoData.new-todo.kind == TodoKind.Once: HorizontalLayout {
                spacing: UiData.padding;
                Button {
                    width: type-cb.width * 1.5;
                    text: TodoData.new-todo.once == TodoData.default-date ? "选择日期" : TodoData.new-todo.once.year + "年" + TodoData.new-todo.once.month + "月" + TodoData.new-todo.once.day + "日";
                    clicked => {
                        date-picker-once.show();
                    }
                }
            }
            if TodoData.new-todo.kind == TodoKind.Weekly: HorizontalLayout {
                spacing: UiData.padding;
                ComboBox {
                    width: type-cb.width;
                    model: weeks;
                    selected(_) => {
                        TodoData.new-todo.week = TodoData.convert-int-to-slintweekday(self.current-index);
                    }
                }
            }
            if TodoData.new-todo.kind == TodoKind.Monthly: HorizontalLayout {
                spacing: UiData.padding;
                SpinBox {
                    width: type-cb.width;
                    maximum: 31;
                    minimum: 1;
                    edited(value) => {
                        TodoData.new-todo.day = value;
                    }
                }
            }
            if TodoData.new-todo.kind == TodoKind.Progress: HorizontalLayout {
                spacing: UiData.padding;
                SpinBox {
                    width: type-cb.width;
                    value: TodoData.new-todo.current-progress;
                    maximum: UiData.spinbox-max;
                    edited(value) => {
                        TodoData.new-todo.current-progress = value;
                    }
                }

                SpinBox {
                    width: type-cb.width;
                    value: TodoData.new-todo.max-progress;
                    maximum: UiData.spinbox-max;
                    edited(value) => {
                        TodoData.new-todo.max-progress = value;
                    }
                }
            }
            note-le := LineEdit {
                min-width: parent.width * 0.1;
                placeholder-text: "可选备注";
            }
        }

        HorizontalLayout {
            width: parent.width;
            spacing: UiData.space;
            Button {
                enabled: TodoData.new-todo.kind != TodoKind.Once;
                width: parent.width * 0.45;
                text: TodoData.new-todo.start-date == TodoData.default-date ? "开始日期" : TodoData.new-todo.start-date.year + "年" + TodoData.new-todo.start-date.month + "月" + TodoData.new-todo.start-date.day + "日";
                clicked => {
                    date-picker-start-date.show();
                }
            }

            Text {
                text: "<->";
                vertical-alignment: center;
                horizontal-alignment: center;
                horizontal-stretch: 1;
            }

            Button {
                enabled: TodoData.new-todo.kind != TodoKind.Once;
                width: parent.width * 0.45;
                text: TodoData.new-todo.end-date == TodoData.default-date ? "截止日期" : TodoData.new-todo.end-date.year + "年" + TodoData.new-todo.end-date.month + "月" + TodoData.new-todo.end-date.day + "日";
                clicked => {
                    date-picker-end-date.show();
                }
            }
        }

        HorizontalLayout {
            spacing: UiData.space;
            text-le := LineEdit {
                accepted(_) => {
                    add-todo();
                }
            }

            default-bt := Button {
                text: "添加待办";
                clicked => {
                    add-todo();
                }
            }
        }

        filter-rt := Rectangle {
            in-out property <int> selected-index;
            in-out property <[string]> filter-text: [
                "今天",
                "全部",
                "单次",
                "每日",
                "每周",
                "每月",
                "进度",
            ];
            border-radius: UiData.border-radius;
            background: UiData.primary-color;
            HorizontalLayout {
                padding-top: UiData.padding;
                padding-bottom: UiData.padding;
                padding-right: UiData.padding-big;
                padding-left: UiData.padding-big;
                spacing: UiData.space-big;
                for i in 7: Text {
                    color: UiData.secondry-text-color;
                    opacity: 0.5;
                    font-size: UiData.font-size-big;
                    text: filter-text[i];
                    TouchArea {
                        clicked => {
                            selected-index = i;
                            TodoData.filter = TodoData.convert-int-to-filter(i);
                        }
                    }

                    states [
                        active when selected-index == i: {
                            opacity: 1;
                        }
                    ]
                    animate opacity {
                        duration: 0.2s;
                        easing: ease-in-out;
                    }
                }
                Text {
                    color: UiData.secondry-text-color;
                    horizontal-stretch: 1;
                    horizontal-alignment: right;
                    font-size: UiData.font-size-big;
                    text: TodoData.filtered-todo-list.length + " / " + TodoData.todo-list.length;
                }
            }
        }

        ListView {
            in-out property <int> selected-todo: -1;
            for todo[i] in TodoData.filtered-todo-list: Rectangle {
                border-radius: UiData.border-radius;
                TouchArea {
                    clicked => {
                        selected-todo = i;
                    }
                }

                states [
                    active when selected-todo == i: {
                        background: UiData.todo-selected-color;
                    }
                ]
                animate background {
                    duration: 0.2s;
                    easing: ease-in-out;
                }
                VerticalLayout {
                    if selected-todo == i: HorizontalLayout {
                        alignment: start;
                        spacing: UiData.space;
                        Button {
                            text: "编辑";
                        }

                        Button {
                            text: "删除";
                            clicked => {
                                TodoData.remove-todo(todo.id);
                                selected-todo = -1;
                            }
                        }

                        Button {
                            text: "完成";
                        }
                    }
                    padding: UiData.padding;
                    spacing: UiData.space;
                    HorizontalLayout {
                        spacing: UiData.space;
                        Rectangle {
                            width: UiData.todo-content-marker;
                            border-radius: UiData.border-radius;
                            background: UiData.primary-color;
                        }

                        VerticalLayout {
                            padding-left: UiData.padding;
                            padding-right: UiData.padding;
                            Text {
                                horizontal-stretch: 1;
                                text: todo.text;
                                wrap: word-wrap;
                                font-size: UiData.font-size-max;
                            }

                            HorizontalLayout {
                                padding-top: UiData.padding;
                                alignment: start;
                                spacing: UiData.space-big;
                                HorizontalLayout {
                                    spacing: UiData.space-small;
                                    Image {
                                        width: UiData.default-font-size;
                                        source: Icons.calendar;
                                    }

                                    Text {
                                        color: UiData.sub-text-color;
                                        text: TodoData.format-todokind(todo.kind);
                                    }
                                }

                                HorizontalLayout {
                                    spacing: UiData.space-small;
                                    Image {
                                        width: UiData.default-font-size;
                                        source: Icons.countdown;
                                    }

                                    if todo.is_expired: Text {
                                        text: "已过期";
                                        color: UiData.warn-color;
                                    }
                                    if !todo.is-expired && todo.kind != TodoKind.Progress: Text {
                                        text: todo.days-to-start == 0 ? "今天" : todo.days-to-start + "天后";
                                        color: UiData.sub-text-color;
                                    }
                                    if !todo.is-expired && todo.kind == TodoKind.Progress: Text {
                                        text: "已完成" + todo.current-progress + "/" + todo.max-progress;
                                        color: UiData.sub-text-color;
                                    }
                                }

                                HorizontalLayout {
                                    spacing: UiData.space-small;
                                    Image {
                                        width: UiData.default-font-size;
                                        source: Icons.note;
                                    }

                                    Text {
                                        overflow: elide;
                                        color: UiData.sub-text-color;
                                        text: todo.note.is-empty ? "暂无备注" : todo.note;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    VerticalLayout {
        horizontal-stretch: 1;
        spacing: UiData.space;
        HorizontalLayout {
            alignment: space-between;
            Button {
                text: "上一个月";
                clicked => {
                    if TodoData.selected_date.month - 1 < 1 {
                        TodoData.selected_date.month = 12;
                        TodoData.selected_date.year -= 1;
                    } else {
                        TodoData.selected_date.month -= 1;
                    }
                    TodoData.update-calendar(TodoData.selected_date);
                }
            }

            Text {
                text: TodoData.selected_date.year + "年" + TodoData.selected_date.month + "月";
                vertical-alignment: center;
                font-size: UiData.font-size-big;
            }

            Button {
                text: "下一个月";
                clicked => {
                    if TodoData.selected_date.month + 1 > 12 {
                        TodoData.selected_date.month = 1;
                        TodoData.selected_date.year += 1;
                    } else {
                        TodoData.selected_date.month += 1;
                    }
                    TodoData.update-calendar(TodoData.selected_date);
                }
            }
        }

        VerticalLayout {
            spacing: UiData.space;
            horizontal-stretch: 1;
            HorizontalLayout {
                spacing: UiData.space;
                for i in 7: Text {
                    height: default-bt.height;
                    text: weeks[i];
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }
            }

            for i in 6: HorizontalLayout {
                spacing: UiData.space;
                for j in 7: TodoCard {
                    day: TodoData.calendar[i * 7 + j].date.day;
                    todo-list: TodoData.calendar[i * 7 + j].todo-list;
                }
            }
        }
    }
}
